kind: pipeline
type: docker
name: osm-arm64

platform:
  arch: arm64
  os: linux

trigger:
  event: 
  - cron
  cron:
  - deploy

steps:
- name: Download-OSM-Data
  image: binho85/osm:arm64
  volumes:
  - name: cache
    path: /data
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
  - chmod +x pipelines/osm.sh
  - pipelines/osm.sh

- name: Extract-POIs
  image: node
  volumes:
  - name: cache
    path: /data
  commands:
  - yarn install
  - yarn pois:generate
- name: git-push
  image: appleboy/drone-git-push
  settings:
    branch: main
    remote: git@github.com:diasfs/osm-proximity.git
    commit: true
    author_name: Fábio Dias
    author_email: binho85@gmail.com
    ssh_key:
      from_secret: SSH_KEY


volumes:
  - name: cache
    host:
      path: /home/ubuntu/osm-cache